
" allow syntax highlighting
filetype plugin on
syntax on

" show numbers
set number

" make tab 4 spaces instead of the default 8
set tabstop=4

" ignore cases when pattern matching
set ignorecase

" search with cases if upper case is used
set smartcase

" auto-indentation, eg. ff previous line starts with a tab, new line will too
set autoindent

" show horizontal line on line cursor is on
set cursorline

" search as characters are entered
set incsearch

" spell checker, F4 turns on/off
" [s for next misspelling, z= to suggest spellings
set spell spelllang=en_gb
set spell!
nnoremap <F4> :set spell!<CR><Bar>:echo "Spell Check: " . strpart("OffOn", 3 * &spell, 3)<CR>

